### ISSUE TITLE
Solution for tsne doesn't work on Python3.5

### ISSUE THREAD

**Issue by zhangfan0726** [danielfrg/tsne#13]
I tried to use it in Python3.5. When I run this command "from tsne import bh_sne" to test I saw error: 

from bh_sne import BH_SNE
File "tsne/bh_sne.pyx", line 2, in init tsne.bh_sne (tsne/bh_sne.cpp:4209)
SystemError: Parent module '' not loaded, cannot perform relative import

I digged a liitle into into it and found that it can be fixed by commenting out line 2 in file tsne/bh_sne.pyx, rebuild and install.
---------------------  tsne/bh_sne.pyx  --------------------
import numpy as np    <--- This is the line I commented out to make it work in Python3.5
cimport numpy as np
cimport cython

I don't know why this fixes the issue but just want leave some reference information for those will encounter the same problem as I did.

**Comment by mzwiessele** [comment]
Same encounter the same error, but commenting the line does not fix the problem. If I comment the line and recompile, it imports fine. But when running bh_sne, it complains about 'np' not being defined...:

```

----> tsne.bh_sne(np.random.normal(0,1,(40,20)))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-2cbae1ab71c4> in <module>()
----> 1 tsne.bh_sne(np.random.normal(0,1,(40,20)))

/home/maxz/Documents/tsne/tsne/__init__.py in bh_sne(data, pca_d, d, perplexity, theta, random_state, copy_data)
     57 
     58     tsne = BH_SNE()
---> 59     Y = tsne.run(X, N, X.shape[1], d, perplexity, theta, seed)
     60     return Y
     61 

/home/maxz/Documents/tsne/tsne/bh_sne.pyx in tsne.bh_sne.BH_SNE.run (tsne/bh_sne.cpp:1571)()

NameError: name 'np' is not defined
> /home/maxz/Documents/tsne/bh_sne.pyx(24)tsne.bh_sne.BH_SNE.run (tsne/bh_sne.cpp:1571)()
```

**Comment by bourbe** [comment]
Same Problem for me. I was not able to run this on 3.5

**Comment by rappdw** [comment]
I was able to work around this by doing the following:

1. in setup.py change the Extension name to be fully qualified, e.g. `name=tsne.bh_sne`
2. in tsne/__init__.py fully qualify the bh_sne(_3d) imports, e.g. `from tsne.bh_sne import BH_SNE`

**Comment by pushlog** [comment]
@rappdw +1

To add: 
After installation use the below line to import:

import tsne.bh_sne as bh_sne

**Comment by mohitkaushikj133** [comment]
File "tsne/bh_sne.pyx", line 12, in init tsne.bh_sne
AttributeError: type object 'tsne.bh_sne.BH_SNE' has no attribute '__reduce_cython__'

**Comment by tranhungnghiep** [comment]
@mohitkaushikj133 #29
