### ISSUE TITLE
It gives syntax error.

### ISSUE THREAD

**Issue by motiur** [danielfrg/tsne#19]
Collecting tsne
  Using cached tsne-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mohammad\AppData\Local\Temp\pip-build-3vw4ikmt\tsne\setup.py", line 61
        print '!!!!!!!!!!!!!', find_packages()
                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------

**Comment by danielfrg** [comment]
That is a useless print that should be removed but it will work in python 2.

**Comment by motiur** [comment]
Nope it is a problem in both version of python : 2.7 and 3.5 as well.

**Comment by mahnunchik** [comment]
Any news?
