### ISSUE TITLE
Installation issues with Ubuntu 17.04 / gcc 4.9.4

### ISSUE THREAD

**Issue by conduit242** [danielfrg/tsne#26]
I'm having an issue installing. Another person posted something similar a few months ago with no resolution here:
https://askubuntu.com/questions/920149/t-sne-installation-error?newreg=1ad2745e23754d6ba070cd3b8fcaa34b

*UPDATE*
I have now tried gcc 4.9.4, gcc 4.8.5, gcc 4.7.4. None work.

```
Failed building wheel for tsne
  Running setup.py clean for tsne
Failed to build tsne
Installing collected packages: Cython, numpy, scipy, tsne
  Running setup.py install for tsne ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0rmDBp/tsne/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-U7ut7H-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Warning: Extension name 'bh_sne' does not match fully qualified name 'tsne.bh_sne' of 'tsne/bh_sne.pyx'
    Compiling tsne/bh_sne.pyx because it depends on /home/rob/.local/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing tsne/bh_sne.pyx
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/tsne
    copying tsne/_version.py -> build/lib.linux-x86_64-2.7/tsne
    copying tsne/__init__.py -> build/lib.linux-x86_64-2.7/tsne
    creating build/lib.linux-x86_64-2.7/tsne/tests
    copying tsne/tests/test_seed.py -> build/lib.linux-x86_64-2.7/tsne/tests
    copying tsne/tests/test_iris.py -> build/lib.linux-x86_64-2.7/tsne/tests
    copying tsne/tests/__init__.py -> build/lib.linux-x86_64-2.7/tsne/tests
    UPDATING build/lib.linux-x86_64-2.7/tsne/_version.py
    set build/lib.linux-x86_64-2.7/tsne/_version.py to '0.1.7'
    running build_ext
    building 'bh_sne' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tsne
    creating build/temp.linux-x86_64-2.7/tsne/bh_sne_src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/rob/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne.o -msse2 -O3 -fPIC -w
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/rob/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne_src/quadtree.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/quadtree.o -msse2 -O3 -fPIC -w
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from tsne/bh_sne_src/quadtree.cpp:15:0:
    tsne/bh_sne_src/quadtree.h: In function ‘double abs(double)’:
    tsne/bh_sne_src/quadtree.h:17:34: error: ‘double abs(double)’ conflicts with a previous declaration
     static inline double abs(double x) { return (x < .0 ? -x : x); }
                                      ^
    In file included from /usr/include/c++/6/math.h:36:0,
                     from tsne/bh_sne_src/quadtree.cpp:10:
    /usr/include/c++/6/cmath:85:3: note: previous declaration ‘constexpr double std::abs(double)’
       abs(double __x)
       ^~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0rmDBp/tsne/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-U7ut7H-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-0rmDBp/tsne/
```
Any ideas what's causing this?

**Comment by derekwisong** [comment]
I experience the same.

**Comment by ReneKat** [comment]
I am having a similar issue, running on Mac OSX Mojave 10.14.6:
`pip install tsne
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting tsne
  Using cached tsne-0.1.8.tar.gz (33 kB)
Requirement already satisfied: Cython>=0.19.1 in /Users/Owl/miniconda3/envs/autometa/lib/python2.7/site-packages (from tsne) (0.29.15)
Requirement already satisfied: numpy>=1.7.1 in /Users/Owl/miniconda3/envs/autometa/lib/python2.7/site-packages (from tsne) (1.16.5)
Collecting scipy>=0.12.0
  Downloading scipy-1.2.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.4 MB)
     |████████████████████████████████| 27.4 MB 14.7 MB/s 
Building wheels for collected packages: tsne
  Building wheel for tsne (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Owl/miniconda3/envs/autometa/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"'; __file__='"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-wheel-6q5r71
       cwd: /private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/tsne
  copying tsne/_version.py -> build/lib.macosx-10.6-x86_64-2.7/tsne
  copying tsne/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/tsne
  creating build/lib.macosx-10.6-x86_64-2.7/tsne/tests
  copying tsne/tests/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
  copying tsne/tests/test_seed.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
  copying tsne/tests/test_iris.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
  UPDATING build/lib.macosx-10.6-x86_64-2.7/tsne/_version.py
  set build/lib.macosx-10.6-x86_64-2.7/tsne/_version.py to '0.1.8'
  running build_ext
  building 'bh_sne' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/tsne
  creating build/temp.macosx-10.6-x86_64-2.7/tsne/bh_sne_src
  gcc -fno-strict-aliasing -I/Users/Owl/miniconda3/envs/autometa/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Owl/miniconda3/envs/autometa/lib/python2.7/site-packages/numpy/core/include -Itsne/bh_sne_src/ -I/Users/Owl/miniconda3/envs/autometa/include/python2.7 -c tsne/bh_sne.cpp -o build/temp.macosx-10.6-x86_64-2.7/tsne/bh_sne.o -I/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /Users/Owl/miniconda3/envs/autometa/include/python2.7/Python.h:19,
                   from tsne/bh_sne.cpp:36:
  /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for tsne
  Running setup.py clean for tsne
Failed to build tsne
Installing collected packages: scipy, tsne
    Running setup.py install for tsne ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/Owl/miniconda3/envs/autometa/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"'; __file__='"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-record-mrcwyN/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Owl/miniconda3/envs/autometa/include/python2.7/tsne
         cwd: /private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.7
    creating build/lib.macosx-10.6-x86_64-2.7/tsne
    copying tsne/_version.py -> build/lib.macosx-10.6-x86_64-2.7/tsne
    copying tsne/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/tsne
    creating build/lib.macosx-10.6-x86_64-2.7/tsne/tests
    copying tsne/tests/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
    copying tsne/tests/test_seed.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
    copying tsne/tests/test_iris.py -> build/lib.macosx-10.6-x86_64-2.7/tsne/tests
    UPDATING build/lib.macosx-10.6-x86_64-2.7/tsne/_version.py
    set build/lib.macosx-10.6-x86_64-2.7/tsne/_version.py to '0.1.8'
    running build_ext
    building 'bh_sne' extension
    creating build/temp.macosx-10.6-x86_64-2.7
    creating build/temp.macosx-10.6-x86_64-2.7/tsne
    creating build/temp.macosx-10.6-x86_64-2.7/tsne/bh_sne_src
    gcc -fno-strict-aliasing -I/Users/Owl/miniconda3/envs/autometa/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Owl/miniconda3/envs/autometa/lib/python2.7/site-packages/numpy/core/include -Itsne/bh_sne_src/ -I/Users/Owl/miniconda3/envs/autometa/include/python2.7 -c tsne/bh_sne.cpp -o build/temp.macosx-10.6-x86_64-2.7/tsne/bh_sne.o -I/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                     from /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                     from /Users/Owl/miniconda3/envs/autometa/include/python2.7/Python.h:19,
                     from tsne/bh_sne.cpp:36:
    /Users/Owl/miniconda3/envs/autometa/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Owl/miniconda3/envs/autometa/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"'; __file__='"'"'/private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-install-SgZ0Qm/tsne/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5s/r0xdrzyj2dl_43mj6jh0cmzc0000gp/T/pip-record-mrcwyN/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Owl/miniconda3/envs/autometa/include/python2.7/tsne Check the logs for full command output.
`

I found this thread, but am unsure how to follow their recommendations:
https://github.com/DmitryUlyanov/Multicore-TSNE/issues/1
