### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by lynnyi** [danielfrg/tsne#27]
Hi, when I try to call:

from tsne import bh_sne

I receive this error:

```
from tsne import bh_sne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tsne/__init__.py", line 6, in <module>
    from bh_sne import BH_SNE
  File "tsne/bh_sne.pyx", line 2, in init tsne.bh_sne
SystemError: Parent module '' not loaded, cannot perform relative import
```

I've used conda to reinstall sklearn which did not resolve this issue.
I'm using python 3.4 and sklearn 0.17

Thanks,
Lynn

**Comment by eric-the-ivysaur** [comment]
I have the same issue.  Python 3.6.  Using `pip` not `conda`.

**Comment by siftikha** [comment]
same issue ubuntu python 3.4

**Comment by tamis-laan** [comment]
Same problem here python 3.5 installed using pip
