### ISSUE TITLE
AttributeError: type object 'tsne.bh_sne.BH_SNE' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by mrgloom** [danielfrg/tsne#29]
After installed via `pip install git+https://github.com/danielfrg/tsne.git`

On `from tsne import bh_sne`

I get:

```
    from bh_sne import BH_SNE
  File "tsne/bh_sne.pyx", line 12, in init tsne.bh_sne
AttributeError: type object 'tsne.bh_sne.BH_SNE' has no attribute '__reduce_cython__'
```

```
pip show Cython
Name: Cython
Version: 0.27.3
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: http://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /home/user/miniconda3/lib/python3.6/site-packages
Requires: 
```

```
which python
/home/user/miniconda3/bin/python
which pip
/home/user/miniconda3/bin/pip
python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Bonnevie** [comment]
I am also experiencing this problem.

**Comment by tranhungnghiep** [comment]
Seems this is because this code (`tsne`) imports an extension class (`BH_SNE`) twice. This causes problem in cython ver. < 0.28, see here: https://github.com/cython/cython/issues/1953

Dev please recompile `tsne` with cython ver. >= 0.28.

**Comment by PyPatel** [comment]
Just run this command. It will build wheel for `tsne.bh_sne`
``` 
 pip install git+https://github.com/alexisbcook/tsne.git 
```

```linux
Building wheels for collected packages: tsne.bh-sne
  Running setup.py bdist_wheel for tsne.bh-sne ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-k9hlejsu/wheels/40/79/77/8941dad3b41383c6b6cf2b64021d45ce054cdd10c245a84887
Successfully built tsne.bh-sne
Installing collected packages: tsne.bh-sne
Successfully installed tsne.bh-sne-0.1.7+5.g3aeafd5
```

**Comment by aydindemircioglu** [comment]
> Just run this command. It will build wheel for `tsne.bh_sne`
> 
> ```
>  pip install git+https://github.com/alexisbcook/tsne.git 
> ```
> **This has been fixed in another fork.** It will look something like this.
> 
> ```
> Building wheels for collected packages: tsne.bh-sne
>   Running setup.py bdist_wheel for tsne.bh-sne ... done
>   Stored in directory: /tmp/pip-ephem-wheel-cache-k9hlejsu/wheels/40/79/77/8941dad3b41383c6b6cf2b64021d45ce054cdd10c245a84887
> Successfully built tsne.bh-sne
> Installing collected packages: tsne.bh-sne
> Successfully installed tsne.bh-sne-0.1.7+5.g3aeafd5
> ```
> After this it will work just fine.

did not work for me out of the box with ubuntu 18.04 and updated scipy/numpy/cython.
had to download the git sources, remove the line 

static inline double abs(double x) { return (x < .0 ? -x : x); }

in quadtree.h, compile and copy the tsne/bh_sne.cpython-36m-x86_64-linux-gnu.so to
/usr/local/lib/python3.6/dist-packages
