### ISSUE TITLE
OS X Yosemite Support?

### ISSUE THREAD

**Issue by jacobmenick** [danielfrg/tsne#3]
I've installed successfully on OSX 10.9.3., but I'm having trouble installing on OS X yosemite (10.10.2). I have all the requirements mentioned besides cblas or openblas.  

When i run 

```
pip install tsne
```

Here's a snippet of the reported error. 
```
    tsne/bh_sne_src/quadtree.cpp:12:10: fatal error: 'cblas.h' file not found
    
    #include <cblas.h>
```

Am I making a mistake or is there no Yosemite support?

**Comment by vzhong** [comment]
I think this has more to do with the fact that the BLAS library can't be found. It's probably not something that this package should solve.

**Comment by jacobmenick** [comment]
Okay, but the "requirements" section of the docs seem to imply that the installation should work without cblas or openblas

Requirements
```
numpy>=1.7.1
scipy>=0.12.0
cython>=0.19.1
cblas or openblas. Tested version is v0.2.5 and v0.2.6 (not necessary for OSX).
```

**Comment by vzhong** [comment]
Yeah that probably has to be updated. Apple removed BLAS from Yosemite. I guess in this sense there is no Yosemite support.

**Comment by jacobmenick** [comment]
Okay, I didn't realize that. I'll get an external BLAS set up in that case.
Thanks.

**Comment by vzhong** [comment]
Sorry my previous post wasn’t exactly accurate. I’m not sure whether the library has been removed or simply moved (I suspect it’s been moved). The caffe folks seemed to also have this problem, and the first post of this thread may be helpful to you:




https://groups.google.com/forum/#!topic/caffe-users/J5YlVnfoo4A

**Comment by jacobmenick** [comment]
Thanks, I got it figured out. So the headers for vecLib have been moved on Yosemite. I was able to get it installed by changing the ```extra_compile_args``` line to the following: 

```
extra_compile_args=['-I/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers']
```

**Comment by danielfrg** [comment]
Thanks for solving this :)

I am reopening so i dont forget to add this fix to the `setup.py`

**Comment by danielfrg** [comment]
Fixed on 0c40dbd6535cb6de80ceae3f9e00850e528d8619

Thanks :)

**Comment by danielfrg** [comment]
New version is up on pypi.

**Comment by jonsedar** [comment]
This is almost certainly me having a strange install, but I had the same issue with not finding `cblas.h`.

I tried the fix suggested by @jacobmenick but that failed, and with some trial and error found that I can only force the installer to find the cblas by changing setup.py to read the exact fully qualified path as given by `locate cblas.h`  i.e.:

`extra_compile_args=['-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers']`

If anyone could comment on why only this works I'd be much obliged - might I have a bodged BLAS install?

OSX 10.10.3, conda 3.7.4, installing from github into a conda environment e.g.

`(my_env)MBP:workingdir jon$ pip install git+https://github.com/danielfrg/tsne.git`

My forked commit shows the difference: https://github.com/jonsedar/tsne/commit/5f1ad8b6d10f144629d7546bd66f9a1c11a90310

Cheers!

**Comment by hualibiorad** [comment]
I have the same problem. I do have cblas.h file in /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers.
but when I run pip install tsne, fatal error: 'cblas.h' file not found.
I am using 10.15.4 macOS laptop. 
I do see the extra_compile_args=['-I/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/Headers'] was changed in the build.py too.
I do not know what is the problem.
