### ISSUE TITLE
Error while installing tsne library

### ISSUE THREAD

**Issue by salilnavgire** [danielfrg/tsne#4]
```
$ pip install tsne
Downloading/unpacking tsne
  Downloading tsne-0.1.1.tar.gz (51kB): 51kB downloaded
  Running setup.py (path:/home/salil/.virtualenvs/ipynb/build/tsne/setup.py) egg_info for package tsne
    
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.19.1 in ./.virtualenvs/ipynb/lib/python2.7/site-packages (from tsne)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib/python2.7/dist-packages (from tsne)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.12.0 in /usr/lib/python2.7/dist-packages (from tsne)
Installing collected packages: tsne
  Running setup.py install for tsne
    skipping 'tsne/bh_sne.cpp' Cython extension (up-to-date)
    building 'bh_sne' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne_src/quadtree.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/quadtree.o -msse2 -O3 -fPIC -w
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    tsne/bh_sne_src/quadtree.cpp:12:19: fatal error: cblas.h: No such file or directory
     #include <cblas.h>
                       ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /home/salil/.virtualenvs/ipynb/bin/python -c "import setuptools, tokenize;__file__='/home/salil/.virtualenvs/ipynb/build/tsne/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qO42Vo-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/salil/.virtualenvs/ipynb/include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/tsne

copying tsne/__init__.py -> build/lib.linux-x86_64-2.7/tsne

running build_ext

skipping 'tsne/bh_sne.cpp' Cython extension (up-to-date)

building 'bh_sne' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/tsne

creating build/temp.linux-x86_64-2.7/tsne/bh_sne_src

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne_src/quadtree.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/quadtree.o -msse2 -O3 -fPIC -w

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

tsne/bh_sne_src/quadtree.cpp:12:19: fatal error: cblas.h: No such file or directory

 #include <cblas.h>

                   ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/salil/.virtualenvs/ipynb/bin/python -c "import setuptools, tokenize;__file__='/home/salil/.virtualenvs/ipynb/build/tsne/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-qO42Vo-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/salil/.virtualenvs/ipynb/include/site/python2.7 failed with error code 1 in /home/salil/.virtualenvs/ipynb/build/tsne
Traceback (most recent call last):
  File "/home/salil/.virtualenvs/ipynb/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

**Comment by danielfrg** [comment]
You need blas, open blas or alternatives. You should be able to install those using the system package manager. Or you could try the anaconda python distribution: http://continuum.io/downloads

**Comment by salilnavgire** [comment]
thanks @danielfrg

**Comment by ashishkrsingh** [comment]
Hi,

I have Fedora 22 [4.2.5-201.fc22.x86_64] and following rpm are installed.

I have similar issue as mentioned above by salilnavgire i.e. /bin/ld: cannot find -lcblas
while atlas, blas, openblas all are installed as shown below:

atlas-3.10.1-21.fc22.x86_64
atlas-devel-3.10.1-21.fc22.x86_64

blas-3.5.0-12.fc22.x86_64
blas-devel-3.5.0-12.fc22.x86_64

openblas-0.2.14-2.fc22.x86_64
openblas-devel-0.2.14-2.fc22.x86_64

openblas-openmp64-0.2.14-2.fc22.x86_64
liblastfm-1.0.9-2.fc22.x86_64
openblas-threads64-0.2.14-2.fc22.x86_64
openblas-serial64-0.2.14-2.fc22.x86_64
openblas-threads-0.2.14-2.fc22.x86_64
openblas-openmp-0.2.14-2.fc22.x86_64

Installation Logs

# pip install tsne
Collecting tsne
  Using cached tsne-0.1.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.19.1 in /usr/lib64/python2.7/site-packages (from tsne)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib64/python2.7/site-packages (from tsne)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.12.0 in /usr/lib64/python2.7/site-packages (from tsne)
Installing collected packages: tsne
  Running setup.py install for tsne
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yuLQEB/tsne/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lI6xVj-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing 'v0.1.5' to '0.1.5'
      normalized_version,
    !!!!!!!!!!!!! ['tsne', 'tsne.tests']
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/tsne
    copying tsne/_version.py -> build/lib.linux-x86_64-2.7/tsne
    copying tsne/__init__.py -> build/lib.linux-x86_64-2.7/tsne
    creating build/lib.linux-x86_64-2.7/tsne/tests
    copying tsne/tests/test_iris.py -> build/lib.linux-x86_64-2.7/tsne/tests
    copying tsne/tests/__init__.py -> build/lib.linux-x86_64-2.7/tsne/tests
    UPDATING build/lib.linux-x86_64-2.7/tsne/_version.py
    set build/lib.linux-x86_64-2.7/tsne/_version.py to 'v0.1.5'
    running build_ext
    building 'bh_sne' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tsne
    creating build/temp.linux-x86_64-2.7/tsne/bh_sne_src
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne.o -msse2 -O3 -fPIC -w
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne_src/quadtree.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/quadtree.o -msse2 -O3 -fPIC -w
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/local/include -Itsne/bh_sne_src/ -I/usr/include/python2.7 -c tsne/bh_sne_src/tsne.cpp -o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/tsne.o -msse2 -O3 -fPIC -w
    g++ -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/tsne/bh_sne.o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/quadtree.o build/temp.linux-x86_64-2.7/tsne/bh_sne_src/tsne.o -L/usr/local/lib -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/bh_sne.so -lcblas
    /bin/ld: cannot find -lcblas
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yuLQEB/tsne/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lI6xVj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yuLQEB/tsne

**Comment by snth** [comment]
I had a similar issue on Ubuntu 14.04. For me the following Ubuntu packages resolved it:

    sudo apt-get install libblas-dev libatlas-base-dev

**Comment by mohitkaushikj133** [comment]
I have same error on mac.

**Comment by dimoibiehg** [comment]
@mohitkaushikj133  This solution works for me

**Comment by ldmtwo** [comment]
Sorry for digging up this old thread. This problem still exists as far as I see it. As of when I last benchmarked these in early 2017, Atlas was slow, OpenBLAS was faster, MKL was fastest (on cpu, because they also make the HW). cuBLAS is also an option. This installer (build script) is not finding what other installers are. I can see that openblas and MKL are both installed on my Ubuntu node and it keeps complaining about blas.h. LD_LIBRARY_PATH has it defined. I fixed this problem in the past with other libraries, but I don't remember how or maybe it's just not working this time. I'm giving up on this and taking the solutions above for now, but maybe I can help the next person get closer to a better answer.

I've tried one of the hacks that usually works, but not here.
export LD_PRELOAD=/opt/intel/mkl/lib/intel64/libmkl_core.so

FYI, you can use this to show where a program searches for libraries. You will have to Google the options. Set it back to empty to stop it.
export LD_DEBUG=libs

When I tried this, I couldn't see that it was even searching for any libs with *cblas* in the name.

**Comment by sidml** [comment]
[This solution](https://github.com/danielfrg/tsne/issues/4#issuecomment-275140455) also works if **libcblas** is not able to be found.
