### ISSUE TITLE
Is it possible to set the seed or random state on bh_sne?

### ISSUE THREAD

**Issue by shuvrobiswas** [danielfrg/tsne#8]
Hi Daniel,

I was wondering if it was possible to set the seed or random state on bh_sne. From my inspection of bh_sne(data, pca_d=None, d=2, perplexity=30.0, theta=0.5) it seems there aren't any explicit arguments for the seed.

I think setting the seed is crucial when bh_sne is being used in part of a larger system, so we can remove the randomness from bh_sne to test other components of the system in isolation. If you can point me in the right direction, that would be awesome (I can send a pull request if you think the seed/random_state should be added to bh_sne).

Best,
Shuvro

**Comment by danielfrg** [comment]
I agree, this is definitely something the library should have.

You would have to go dive a little bit to the C code and set the seed in `randn()`: https://github.com/danielfrg/tsne/blob/1aa5f39849a37842b50da320cbefe313397dc15a/tsne/bh_sne_src/tsne.cpp#L101

**Comment by danielfrg** [comment]
Fixed on https://github.com/danielfrg/tsne/pull/12

**Comment by Dofollow** [comment]
Hello, Daniel!
Sorry, how can I use "random_state" in bh_sne? When I try do it, I get error  
'bh_sne() got an unexpected keyword argument 'random_state'
